### ISSUE TITLE
Command 'slackord' is already registered

### ISSUE THREAD

**Issue by joepio** [thomasloupe/Slackord1#4]
Thanks for creating this script! Unfortunately, I'm having problems when executing the very last step:

```
iscord.errors.ClientException: Command slackord is already registered.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "slackord.py", line 49, in Output
    @bot.command(pass_context=True)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1163, in decorator
    self.add_command(result)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 1071, in add_command
    raise discord.ClientException('Command {0.name} is already registered.'.format(command))
discord.errors.ClientException: Command slackord is already registered.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "slackord.py", line 26, in SpawnTokenWindow
    bot.run(botToken)
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 614, in run
    loop.add_signal_handler(signal.SIGINT, lambda: loop.stop())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/unix_events.py", line 86, in add_signal_handler
    self._check_closed()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

If I understand this correctly, the Discord API returns an error because the 'slackord' name can only be registered once. Maybe this is due to a change in their API?

Anyways, in my case it resulted in nothing happening in the interface after selecting a JSON file and pasting a Token. I think an exception should be printed when this happens.

**Comment by thomasloupe** [comment]
Are you using 0.5 or 1.0 when you get this issue? I'll try and reproduce this.

**Comment by joepio** [comment]
1.0

Just noticed you released a 2.0. Why not use this repo for that?

**Comment by thomasloupe** [comment]
Good question. They're completely different codebases (Python/Tkinter), and 2.0 uses .NET 4.8. This repo is for those who want to run Slackord in linux/unix. I may merge them in the near future, but I'll have to point those users to previous releases and I'm concerned about doing that given their significant code differences.

If you'd like to give 2.x a run, please feel free. I'll still look into this particular issue.

**Comment by joepio** [comment]
Thanks! 😇

**Comment by thomasloupe** [comment]
Did you, by chance, have the bot selected as a public bot or did you have more than one Slackord bot set up in your developer panel?
