### ISSUE TITLE
Import process is just hanging and/or moving really slowly

### ISSUE THREAD

**Issue by emmahsax** [thomasloupe/Slackord1#5]
I am running on MacOS M1 Pro, Monterey 12.5.1.

I followed the instructions in the README exactly, and am running:

```bash
$ pip3 --version
pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
$ python3 --version
Python 3.10.6
```

First, I got an error around tkinter:

```bash
$ python3 slackord.py
Traceback (most recent call last):
  File "/Users/emmasax/projects/Slackord/slackord.py", line 9, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

To resolve, I ran `brew install python-tk`.

But then I got this error:

```bash
$ python3 slackord.py      
Traceback (most recent call last):
  File "/Users/emmasax/projects/Slackord/slackord.py", line 14, in <module>
    bot = commands.Bot(command_prefix='!')
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'
```

And I edited `slackord.py` to change line 14:

```diff
- bot = commands.Bot(command_prefix='!')
+ bot = commands.Bot(command_prefix='!', intents=discord.Intents.default())
```

And finally, it seemed to be working right. But when I loaded the first JSON file, put in my bot APi key, and type`!slackord` into my Discord channel, it just seems to hang and nothing happens.

My command line now shows this:

```bash
$ python3 slackord.py
2022-08-23 22:18:11 WARNING  discord.ext.commands.bot Privileged message content intent is missing, commands may not work as expected.
2022-08-23 22:18:11 INFO     discord.client logging in using static token
2022-08-23 22:18:11 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: cff66ec716b1589256..............).
```

and is just hanging and I'm not seeing anything appear in my Discord channel. Is this normal? How long is the import process normally supposed to take?

**Comment by thomasloupe** [comment]
Hi @emmahsax!

Thanks for reporting the issue!

This version of Slackord now requires the two following intents:
`messages`, and `message_content`. Specifying `default` or `all` will not work as expected and will hang the UI.

I have updated Slackord so that the required intents are requested.
If you grab the latest commit, it should work fine now. Please feel free to confirm that for me.

I have also updated the README to reflect installation of tk and discord.py, with specific instructions on OS as well.
I would also like to recommend Slackord2 over this version of Slackord. You'd have to run it in Wine or equivalent VM as it's for Windows, but it works much better and imports more data. You can find it here if you wish to use it instead: https://github.com/thomasloupe/Slackord2.

**Comment by emmahsax** [comment]
@thomasloupe With the new commits from `master`, I now get this error:
```
$ python3 slackord.py
2022-08-24 09:13:43 INFO     discord.client logging in using static token
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/emmasax/projects/Slackord/slackord.py", line 30, in SpawnTokenWindow
    bot.run(botToken)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/client.py", line 828, in run
    asyncio.run(runner())
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.10/site-packages/discord/client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/client.py", line 672, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
```

**Comment by emmahsax** [comment]
@thomasloupe Thank you so much for your response! Yes, I got it working. I realized that Slackord2 would probably be fancier, but it was super easy for me to work with the python project on my machine, since Slackord2 was designed for windows, and so this did exactly what I needed. Thank you again!
